<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>Title of page goes here</title>

	<!-- include an external style sheet -->
	<link rel="stylesheet" href="style.css">  

	<!-- include an external JavaScript file -->
	<script src="script.js" async></script>
</head>



<body>
	
	<div class="header">
	<h1>Rambook</h1>
	
	</div>
	
	<div class="headerlinks">
		<a href="/~ronald/rambook/?number=0">Page 1</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;
		<a href="/~ronald/rambook/?number=1">Page 2</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;
		<a href="/~ronald/rambook/?number=2">Page 3</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;
		<a href="/~ronald/rambook/?number=3">Page 4</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;
		<a href="form.php">Form</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;
	</div>
