<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>Rambook</title>

	<!-- include an external style sheet -->
	<link rel="stylesheet" href="style.css">  

	<!-- include an external JavaScript file -->
	<script src="script.js" async></script>
</head>



<body>
	
	<div class="header">
	<h1><a class="logo" href="./">Rambook</a></h1>
	
	</div>
	
	<div class="navbar">
		<a class="navbarlink" href="./">Home</a>
		<a class="navbarlink" href="./form.php">Form</a>
	</div>
