<!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <title>Title of page goes here</title>
    
    <!-- include an external style sheet -->
    <link rel="stylesheet" href="style.css">  
    
    <!-- include an external JavaScript file -->
    <script src="script.js" async></script>
	
  </head>
  
  <body>
	